# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: windows-latest

variables:
  ORG: 'vinima'
  FEED_ID: '8aec59e1-6117-46e0-9b4b-148f6a7eecc7'
  GROUP_ID: 'MyGroup'
  ARTIFACT_ID: 'myFirstApp'
  VERSION: '1.0-SNAPSHOT'
  FILENAME: 'myFirstApp-1.0-20230508.222359-1.jar'

steps:
- task: PowerShell@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    filePath: 'Download-MavenPackage.ps1'
    arguments: '-Organization "$(ORG)" -FeedId "$(FEED_ID)" -GroupId "$(GROUP_ID)" -ArtifactId "$(ARTIFACT_ID)" -Version "$(VERSION)" -FileName "$(FILENAME)" -OutputDirectory "$(System.ArtifactsDirectory)\powershell"'
- task: DownloadPackage@1
  inputs:
    packageType: 'maven'
    feed: '/8aec59e1-6117-46e0-9b4b-148f6a7eecc7'
    view: 'dfb72d12-b87c-4f5b-bc1b-803c8412ede8'
    definition: '33e81c24-2b92-42ec-a191-a28b589b085d'
    version: '1.0-snapshot'
    files: 'myFirstApp-1.0-20230508.222359-1.jar'
    downloadPath: '$(System.ArtifactsDirectory)\task'
- publish: $(System.ArtifactsDirectory)
  artifact: maven-$(FILENAME)